stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - my_data/wine.csv
    outs:
      - data/train_data/train.csv
      - data/test_data/test.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/train_data/train.csv
      - data/test_data/test.csv
    outs:
      - data/preprocessed/train_preprocessed.csv
      - data/preprocessed/test_preprocessed.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/preprocessed/train_preprocessed.csv
      - data/preprocessed/test_preprocessed.csv
    outs:
      - data/feature_engineered/train_engineered.csv
      - data/feature_engineered/test_engineered.csv

  model_training:
    cmd: python src/model_training.py
    deps:
      - data/feature_engineered/train_engineered.csv
      - data/feature_engineered/test_engineered.csv
    outs:
      - data/models/random_forest_model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - data/models/random_forest_model.pkl
      - data/feature_engineered/test_engineered.csv
    outs:
      - data/evaluation_results/evaluation_metrics.txt
