name: Continuous Integration

# Trigger on push events for the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Runner type; can be Windows, Mac, or Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v2   # Checkout code from your repository

      - name: Set up Python
        uses: actions/setup-python@v2   # Set up the python environment
        with:
          python-version: 3.9   # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Install project dependencies

      - name: Run tests
        run: |
          pytest   # Run your tests here (can be modified based on your testing framework)

      - name: Upload coverage reports
        if: success()  # If tests succeed, upload coverage reports
        uses: codecov/codecov-action@v2
